export const SIGNIN = 'SIGNIN';
export const LOGOUT = 'LOGOUT';

export const PROJECTSN = 'PROJECTSN';
export const USERN = 'USERN';

export const CREATEUSER = 'CREATEUSER';
export const UPDATEUSER = 'UPDATEUSER';
export const ALLREGULARUSER = 'ALLREGULARUSER';

export const CREATEPROJECT = 'CREATEPROJECT';
export const ALLPROJECTS = 'ALLPROJECTS';
export const PROJECTUPDATE = 'PROJECTUPDATE';

export const CREATETASK = 'CREATETASK';
export const ALLTASKS = 'ALLTASKS';
export const UPDATETASK = 'UPDATETASK';
export const UPDATECOMPLETIONTASK = 'UPDATECOMPLETIONTASK';